language: node_js
node_js: stable

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      if: branch = develop AND type = push
      before_script: pip install --user awscli
      script: npm run build-docs
      after_success: aws s3 sync ./webout s3://pm-schemas/ --delete --follow-symlinks

notifications:
  slack:
    secure: Fdl/sQMTl86jYN1r1CRRRQRgyFoslvrhkkfnM2JSdx4gODPgyg4nCPSKtU5j9wpSbbkq9A+YBeFv+Suh+xYNviegqa0AZbztydfFzVDS7xw43B/uR9Y4LwaP5Kis1WGuIOHawwFISNO3hTUei6aybKiKKlxvfqrARJaO01+Xxrg=